name: Build & push to registries

on:
  push:
    branches:
      - main

    tags:
      - v*

env:
  IMAGE_NAME: goose-docker

jobs:
  build_and_push:
    strategy:
      matrix:
        image: [ "goose-docker", "cmd" ]

    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'amd64,arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.19.2
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate names
        id: names
        run: |
          TARGET_IMAGE_NAME=${{ env.IMAGE_NAME }}
          [ "${{ matrix.image }}" != ${{ env.IMAGE_NAME }} ] && TARGET_IMAGE_NAME="${{ env.IMAGE_NAME }}-${{ matrix.image }}"
          
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$TARGET_IMAGE_NAME
          DOCKER_HUB_IMAGE_ID=${{ vars.DOCKERHUB_GROUP }}/$TARGET_IMAGE_NAME

          DOCKERFILE="Dockerfile"
           [ "${{ matrix.image }}" != ${{ env.IMAGE_NAME }} ] && DOCKERFILE="${{ matrix.image }}.Dockerfile"

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          DOCKER_HUB_IMAGE_ID=$(echo $DOCKER_HUB_IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref_name }}")
          
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          
          echo "github.ref=${{ github.ref }}"
          echo "github.ref_name=${{ github.ref_name }}"
          echo "DOCKERFILE=$DOCKERFILE"
          echo "IMAGE_ID=$IMAGE_ID"
          echo "DOCKER_HUB_IMAGE_ID=$DOCKER_HUB_IMAGE_ID"
          echo "VERSION=$VERSION"
          
          echo "DOCKERFILE=$DOCKERFILE" >> $GITHUB_ENV
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "DOCKER_HUB_IMAGE_ID=$DOCKER_HUB_IMAGE_ID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          file: ${{ env.DOCKERFILE }}
          tags: |
            ${{ env.IMAGE_ID }}:${{ env.VERSION }}
            ${{ env.DOCKER_HUB_IMAGE_ID }}:${{ env.VERSION }}
          labels: | 
            org.opencontainers.image.vendor="${{ github.repository_owner }}"
            org.opencontainers.image.title="${{ vars.LABEL_TITLE }}"
            org.opencontainers.image.description="${{ vars.LABEL_DESCRIPTION }}"
            org.opencontainers.image.source="${{ github.server_url }}/${{ github.repository }}"
            org.opencontainers.image.licenses="${{ vars.LABEL_LICENSES }}"
            org.opencontainers.image.version="v${{ env.VERSION }}"

      - name: Test docker compose
        run: |
          VERSION=${{ env.VERSION }}
          sed -i "s/3.25.0/$VERSION/" .env
          cat .env
          
          docker compose up -d
          docker compose down
